/******************************************************
TO_DATE, TO_TIMESTAMP 로 문자열을 DATE, TIMESTAMP로 변환.
TO_CHAR로 DATE, TIMESTAMP를 문자열로 변환.
*******************************************************/

-- 문자열을 FORMATING에 따라 DATE, TIMESTAMP로 변환.
SELECT TO_DATE('2022-01-01', 'YYYY-MM-DD');

SELECT TO_TIMESTAMP('2022-01-01', 'YYYY-MM-DD');

SELECT TO_TIMESTAMP('2022-01-01 14:36:52', 'YYYY-MM-DD HH24:MI:SS')

-- DATE를 TIMESTAMP로 변환
SELECT TO_DATE('2022-01-01', 'YYYY-MM-DD')::TIMESTAMP;

-- TIMESTAMP를 TEXT로 변환
SELECT TO_TIMESTAMP('2022-01-01', 'YYYY-MM-DD')::TEXT;

-- TIMESTAMP를 DATE로 변환.
SELECT TO_TIMESTAMP('2022-01-01 14:36:52', 'YYYY-MM-DD HH24:MI:SS')::DATE


-- TO_DATE, TO_TIMESTAMP, TO_CHAR 실습-1
    WITH
TEMP_01 AS (
SELECT A.*
	  , TO_CHAR(HIREDATE, 'YYYY-MM-DD') AS HIREDATE_STR
FROM HR.EMP A
)
SELECT EMPNO, ENAME, HIREDATE, HIREDATE_STR
     , TO_DATE(HIREDATE_STR, 'YYYY-MM-DD') AS HIREDATE_01
     , TO_TIMESTAMP(HIREDATE_STR, 'YYYY-MM-DD') AS HIRETIME_01
     --, TO_TIMESTAMP(HIREDATE_STR, 'YYYY-MM-DD HH24:MI:SS') AS HIRETIME_02
     , TO_CHAR(HIREDATE, 'YYYYMMDD HH24:MI:SS') AS HIREDATE_STR_01
     , TO_CHAR(HIREDATE, 'MONTH DD YYYY') AS HIREDATE_STR_02
     , TO_CHAR(HIREDATE, 'MONTH DD YYYY') AS HIREDATE_STR_03
     , TO_CHAR(HIREDATE, 'YYYY MONTH') AS HIREDATE_STR_04
     -- W 는 해당 달의 WEEK, D는 일요일(1) 부터 토요일(7)
     , TO_CHAR(HIREDATE, 'MONTH W D') AS HIREDATE_STR_05
     -- DAY는 요일을 문자열로 나타냄.
     , TO_CHAR(HIREDATE, 'MONTH, DAY') AS HIREDATE_STR_06
FROM TEMP_01;

-- TO_DATE, TO_TIMESTAMP, TO_CHAR 실습-2
WITH
    TEMP_01 AS (
        SELECT A.*
             , TO_CHAR(HIREDATE, 'YYYY-MM-DD') AS HIRE_DATE_STR
             , HIREDATE::TIMESTAMP AS HIRETIME
        FROM HR.EMP A
    )
SELECT EMPNO, ENAME, HIREDATE, HIRE_DATE_STR, HIRETIME
     , TO_CHAR(HIRETIME, 'YYYY/MM/DD HH24:MI:SS') AS HIRETIME_01
     , TO_CHAR(HIRETIME, 'YYYY/MM/DD PM HH12:MI:SS') AS HIRETIME_02
     , TO_TIMESTAMP('2022-03-04 22:10:15', 'YYYY-MM-DD HH24:MI:SS') AS TIMESTAMP_01
     , TO_CHAR(TO_TIMESTAMP('2022-03-04 22:10:15', 'YYYY-MM-DD HH24:MI:SS'), 'YYYY/MM/DD AM HH12:MI:SS') AS TIMESTR_01
FROM TEMP_01;