/************************************
   GROUP BY ROLLUP
*************************************/

--DEPTNO + JOB레벨 외에 DEPT내의 전체 JOB 레벨(결국 DEPT레벨), 전체 AGGREGATION 수행.
SELECT DEPTNO, JOB, SUM(SAL)
FROM HR.EMP
GROUP BY ROLLUP(DEPTNO, JOB)
ORDER BY 1, 2;


-- 상품 카테고리 + 상품별 매출합 구하기
SELECT C.CATEGORY_NAME, B.PRODUCT_NAME, SUM(AMOUNT)
FROM NW.ORDER_ITEMS A
	JOIN NW.PRODUCTS B ON A.PRODUCT_ID = B.PRODUCT_ID
	JOIN NW.CATEGORIES C ON B.CATEGORY_ID = C.CATEGORY_ID
GROUP BY C.CATEGORY_NAME, B.PRODUCT_NAME
ORDER BY 1, 2
;

-- 상품 카테고리 + 상품별 매출합 구하되, 상품 카테고리 별 소계 매출합 및 전체 상품의 매출합을 함께 구하기
SELECT C.CATEGORY_NAME, B.PRODUCT_NAME, SUM(AMOUNT)
FROM NW.ORDER_ITEMS A
	JOIN NW.PRODUCTS B ON A.PRODUCT_ID = B.PRODUCT_ID
	JOIN NW.CATEGORIES C ON B.CATEGORY_ID = C.CATEGORY_ID
GROUP BY ROLLUP(C.CATEGORY_NAME, B.PRODUCT_NAME)
ORDER BY 1, 2
;

-- 년+월+일별 매출합 구하기
-- 월 또는 일을 01, 02와 같은 형태로 표시하려면 TO_CHAR()함수, 1, 2와 같은 숫자값으로 표시하려면 DATE_PART()함수 사용.
SELECT TO_CHAR(B.ORDER_DATE, 'YYYY') AS YEAR
	, TO_CHAR(B.ORDER_DATE, 'MM') AS MONTH
	, TO_CHAR(B.ORDER_DATE, 'DD') AS DAY
	, SUM(A.AMOUNT) AS SUM_AMOUNT
FROM NW.ORDER_ITEMS A
	JOIN NW.ORDERS B ON A.ORDER_ID = B.ORDER_ID
GROUP BY TO_CHAR(B.ORDER_DATE, 'YYYY'), TO_CHAR(B.ORDER_DATE, 'MM'), TO_CHAR(B.ORDER_DATE, 'DD')
ORDER BY 1, 2, 3;

-- 년+월+일별 매출합 구하되, 월별 소계 매출합, 년별 매출합, 전체 매출합을 함께 구하기
WITH
TEMP_01 AS (
    SELECT TO_CHAR(B.ORDER_DATE, 'YYYY') AS YEAR
        , TO_CHAR(B.ORDER_DATE, 'MM') AS MONTH
        , TO_CHAR(B.ORDER_DATE, 'DD') AS DAY
        , SUM(A.AMOUNT) AS SUM_AMOUNT
    FROM NW.ORDER_ITEMS A
        JOIN NW.ORDERS B ON A.ORDER_ID = B.ORDER_ID
    GROUP BY ROLLUP(TO_CHAR(B.ORDER_DATE, 'YYYY'), TO_CHAR(B.ORDER_DATE, 'MM'), TO_CHAR(B.ORDER_DATE, 'DD'))
)
SELECT CASE WHEN YEAR IS NULL THEN '총매출' ELSE YEAR END AS YEAR
	, CASE WHEN YEAR IS NULL THEN NULL
		ELSE CASE WHEN MONTH IS NULL THEN '년 총매출' ELSE MONTH END
	  END AS MONTH
	, CASE WHEN YEAR IS NULL OR MONTH IS NULL THEN NULL
		ELSE CASE WHEN DAY IS NULL THEN '월 총매출' ELSE DAY END
	  END AS DAY
	, SUM_AMOUNT
FROM TEMP_01
ORDER BY YEAR, MONTH, DAY
;
