/************************************
   GROUP BY CUBE
*************************************/

-- DEPTNO, JOB의 가능한 결합으로 GROUP BY 수행.
SELECT DEPTNO, JOB, SUM(SAL)
FROM HR.EMP
GROUP BY CUBE(DEPTNO, JOB)
ORDER BY 1, 2;

-- 상품 카테고리 + 상품별 + 주문처리직원별 매출
SELECT C.CATEGORY_NAME, B.PRODUCT_NAME, E.LAST_NAME||E.FIRST_NAME AS EMP_NAME, SUM(AMOUNT)
FROM NW.ORDER_ITEMS A
	JOIN NW.PRODUCTS B ON A.PRODUCT_ID = B.PRODUCT_ID
	JOIN NW.CATEGORIES C ON B.CATEGORY_ID = C.CATEGORY_ID
	JOIN NW.ORDERS D ON A.ORDER_ID = D.ORDER_ID
	JOIN NW.EMPLOYEES E ON D.EMPLOYEE_ID = E.EMPLOYEE_ID
GROUP BY C.CATEGORY_NAME, B.PRODUCT_NAME, E.LAST_NAME||E.FIRST_NAME
ORDER BY 1, 2, 3
;

--상품 카테고리, 상품별, 주문처리직원별 가능한 결합으로 GROUP BY 수행
SELECT C.CATEGORY_NAME, B.PRODUCT_NAME, E.LAST_NAME||E.FIRST_NAME AS EMP_NAME, SUM(AMOUNT)
FROM NW.ORDER_ITEMS A
	JOIN NW.PRODUCTS B ON A.PRODUCT_ID = B.PRODUCT_ID
	JOIN NW.CATEGORIES C ON B.CATEGORY_ID = C.CATEGORY_ID
	JOIN NW.ORDERS D ON A.ORDER_ID = D.ORDER_ID
	JOIN NW.EMPLOYEES E ON D.EMPLOYEE_ID = E.EMPLOYEE_ID
GROUP BY CUBE(C.CATEGORY_NAME, B.PRODUCT_NAME, E.LAST_NAME||E.FIRST_NAME)
ORDER BY 1, 2, 3
;